### ISSUE TITLE
blending an image with transparency looks weird

### ISSUE THREAD

**Issue by orlando** [jcupitt/ruby-vips#28]
Hello, im working in porting some code that uses Rmagick to ruby-vips. I'm trying to make blended images with a color using `VIPS::Image.black(x,y,4)` and then applying a linear transformation to paint it to desired color.. like

``` ruby
  background = VIPS::Image.black(width,height,4)
  # (Image.hex2rgb(options.blend) => returns an array of rgb, like [255,0,0] in case of red
  background = background.lin([1,1,1,1],(Image.hex2rgb(options.blend)+[255*options.opacity/100.0]))

  #blend
  @process_image.blend(@process_image,background)
```

when i make the blend the transparency looks really weird.

[Rmagick Result](https://dl.dropbox.com/u/6399431/transparent.blend%3Df20000%26opacity%3D70.png)
[ruby-vips Result](https://dl.dropbox.com/u/6399431/transparent2.png)

any suggestions will be appreciated.. thanks for your time

**EDIT**

I'm pretty sure this is because I'm doing something (or everything) wrong

**Comment by gasi** [comment]
I was able to port @jcupitt Ruby approach to the following C code:
https://github.com/gasi/sharp/blob/e18b5d3736af4e1f7e768c5cd622dfabae7a08c7/test/unit/composite.c#L70-L144

Feedback welcome (C/VIPS newbie here) :smile: 

_P.S. Having worked with VIPS for a few hours now and being a C beginner, I was wondering if you have considered / it is possible to build a more general functional interface (as in functional programming) to VIPS, @jcupitt? I wish I could do `map`, `fold`, etc. over images with custom functions similar to how Haskell works. This means that something like creating `negative` would be `map (\x -> 255 - x) image` instead of all of https://gist.github.com/jcupitt/8452027. Then again, I might be missing some obvious complexity_
_P.P.S. Great work on VIPS, @jcupitt!_ :heart:

**Comment by gasi** [comment]
Generally, I agree with @jcupitt and wish there was a built-in `vips_composite(in1, in2, out, "mode", VIPS_BLEND_MODE_OVER | VIPS_BLEND_MODE_DARKEN | …, NULL)` function :smile:

**Comment by jcupitt** [comment]
Yes @gasi I agree I like the functional style very much. I worked on Haskell for my PhD, years and years ago. The vips API is essentially functional: no side-effects plus lazy evaluation plus memoisation.

nip2 is dynamically typed Haskell (almost) plus a gui. The sobel filter (for example) is defined as:

```
action x 
	= map_unary sobel x
{
	sobel im
		= abs (a - 128) + abs (b - 128)
	{
		a = conv filter_sobel im;
		b = conv (rot270 filter_sobel) im;
	}

	filter_sobel = Matrix_con 1 128 [[1, 2, 1], [0, 0, 0], [-1, -2, -1]];
}
```

You can't map over pixels, it'd be too slow, but you can use a functional language to glue the vips vector primitives together. You can use nip2 as a command interpreter.

**Comment by gasi** [comment]
> Yes @gasi I agree I like the functional style very much. I worked on Haskell for my PhD, years and years ago.

Awesome!

> The vips API is essentially functional: no side-effects plus lazy evaluation plus memoisation.

Agreed and that’s why I was wondering how hard it’d be to add some higher order functions that would let users pass in custom functions that are applied to each pixel. Forgive my ignorance, but why is it too slow to map over pixels? For example, `vips_abs` & Co. seem to do it: https://github.com/jcupitt/libvips/blob/4e96db4216921db9b7cb68c165c3aa484eae0ca7/libvips/arithmetic/arithmetic.c#L503 Would it be possible to expose something like this in the C interface where one could supply one’s own `process_line`? :smile: 

> nip2 is dynamically typed Haskell (almost) plus a gui. The sobel filter (for example) is defined as

That is a wicked cool example :+1: 


I work on a Node.js app which uses the [`sharp`](https://github.com/lovell/sharp) `libvips` binding. Would it be possible to build a binding to nip2 that would allow for easier creation of new VIPS operations?

**Comment by jcupitt** [comment]
Ah OK, sorry, I though you meant in Ruby. Yes, in C you can make a class that loops over an image in a certain way, then subclass that to make a particular operator. vips_invert() is done like this:

https://github.com/jcupitt/libvips/blob/master/libvips/arithmetic/invert.c

You could do that in a functional style too, of course. The base class could offer a function that took a buffer processor as an argument. 

vips7 worked like this, but for vips8 we've shifted to a more OO style The reason is that we use the class hierarchy for introspection. If all image processing operations are classes, we can discover them at runtime and generate the bindings automatically. 

The new vips8 python binding is done like this: there's a few 100 lines of Python to set everything up, then the rest of the binding is made at runtime from walking the vips class structure. This means that bindings update automatically for new library features, and they can be written in pure Python (or Ruby or whatever) with no C, so they are very easy to port. 

I've done a couple of Ruby bindings for vips in this style, but neither is production-ready, unfortunately :-( maybe another few months.

**Comment by jcupitt** [comment]
I meant to add, the new Python binding lets you write stuff like this:

```python
im = (im * 12 + 32).cast("uchar").resize(0.25)
```

ie. you can write filters directly in Python itself. This works (obviously) by building a pipeline of vips operators. When the pipeline runs it's perhaps about half the speed you'd get by writing that expression in C and implementing it directly. 

The reason it's quick is due to the way vips does tiling and threading. Images are processed in small tiles, usually around 128x128 pixels. A thread will read 128x128 pixels from the source image, then do each of the operations in the pipeline in turn on that 128x128 pixel buffer, so in this case times, then add, then cast, then resize. As it starts each operation, the output of the previous one will still be in L1 or maybe L2 cache -- it never needs to hit main memory. 

Summary: because vips runs within the processor cache, chained operations are almost as quick as directly coded operations. 

So -- vips aims to provide a fairly complete set of fast primitive vector operations, plus an efficient way to chain them together. You can make new filters by simply constructing pipelines of these basic operations, and your filters will run pretty quickly and not need much memory.

**Comment by jcupitt** [comment]
Ahem, final mail. Here's the source to the Python binding:

https://github.com/jcupitt/libvips/blob/master/python/Vips.py

It's about 1,000 lines, but most of that is defining convenience functions plus all the operator overloads, the core is very small, under 200 lines. A javascript binding in that style would be a nice thing to have.

The difficulty is that it uses gobject-introspection and you need that for your JS first. There's a nice gobject-introspection for spidermonkey:

https://wiki.gnome.org/Projects/Gjs

but I don't know of a good one for node. There's node-gir but I think it may have been abandoned and I don't know what state it's in.

**Comment by jcupitt** [comment]
composite.c looks nice. I made a couple of small changes:

* I put the processing into a function rather than main(), it makes reuse easier.
* I added a `handle`: a thing which images are relative to. This makes unreffing easier and safer.
* I set it to do the processing in scRGB. This is a linear light space and ought to give nicer results, but maybe straight sRGB would be better, since that's probably what people are used to. 

https://gist.github.com/jcupitt/abacc012e2991f332e8b

**Comment by jcupitt** [comment]
... I updated the gist, I thought of a speedup. The vips_linear1() that unnormalises the alpha can have a `uchar` option.

**Comment by gasi** [comment]
Thanks for providing so much background on the design rationale behind VIPS :smile: 

> I meant to add, the new Python binding lets you write stuff like this:
> 
> `im = (im * 12 + 32).cast("uchar").resize(0.25)`

This is really elegant :gem: It’d be great if we could do that in [`sharp`](https://github.com/lovell/sharp) at some point. Of course, JavaScript doesn’t support operator overloading, but even auto-generating Node.js bindings for all VIPS operations would be great. /cc @lovell

Thanks for the pointers to https://github.com/creationix/node-gir and https://wiki.gnome.org/Projects/Gjs.

> composite.c looks nice. I made a couple of small changes:

Thanks for your improvements to `composite.c`. I much prefer your temporary images using an array that is automatically cleaned up after the operation has completed. I also learned something new about the colo(u)r space conversion that @lovell also pointed out in https://github.com/lovell/sharp/issues/97#issuecomment-96992048. I will compare your approach against mine to see whether it matches the output we get from our existing system, which is a restriction I have to obey.

Would you be willing to release your changes under the Apache License so I can integrate it with `sharp`? If so, I’d appreciate if you could add a license header to your `composite2.c` gist. See: https://github.com/lovell/sharp/blob/master/LICENSE

Thanks again for your work on VIPS, on being so responsive, and generous in explaining how things work :heart:

**Comment by jcupitt** [comment]
As of libvips 8.6, there's now a `composite` operator based in part on this issue, so I think we can close.
