### ISSUE TITLE
making a LUT

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/ruby-vips#76]
_Paul mailed this question_

I asked you a few weeks ago about doing a Photoshop “levels” or “curves” kind of transformation on an image and you confirmed that building a histogram and then using it with maplut is the way to go.

Here is the documentation for buildlut:

http://www.vips.ecs.soton.ac.uk/supported/current/doc/html/libvips/libvips-create.html#vips-buildlut

It says "This operation builds a lookup table from a set of points. Intermediate values are generated by piecewise linear interpolation.”. Sounds like what I need — feed in a set of coordinates for straight line segments of a mapping curve (would be only a handful) and then this will build it out as a full histogram.

So I need to create the “image" for the "set of coordinates”, as shown on the above documentation page.

But I can’t find a way to poke a pixel value into an image (from Ruby). There is vips_draw_point() but that doesn’t appear in the Ruby interface. Or is there another easy way to create a 2 x 2 image from an array of numbers?

**Comment by jcupitt** [comment]
There are a few ways to make a LUT. The simplest is just to pass a Ruby array to `Vips::Image.new_from_array`:

http://www.rubydoc.info/gems/ruby-vips/1.0.0/Vips/Image#new_from_array-class_method

(Ooop, the markup seems to be broken, I'll have a look).

Pass a 256-element array to make a LUT suitable for 8-bit images.

You can use `Vips::Image.identity` to make a linear ramp, then use math operations on it to change it to any shape you like.

http://www.rubydoc.info/gems/ruby-vips/1.0.0/Vips/Image#identity-class_method

For example:

```
lut = Vips::Image.identity
lut = lut ** 0.5
lut = 255 * lut / lut.max
```

To make a square-root lut.

Finally, as you said there's buildlut. Use `.new_from_array` to make the argument.

**Comment by PaulHowson** [comment]
Thanks John. I got it working for 8-bit images: create an array of "points" using new_from_array then pass to buildlut to create a 256 element x 8-bit lut. Then use with maplut on an 8-bit image. Works perfectly.

However, my source images are 16-bit (from 10-bit scans). So I need a lut which is 65536 elements long x 8-bits (for the purposes of correlation the image samples can be mapped to 8-bit). Problem is that new_from_array seems to assume that the values for the new array are 8-bit numbers. For buildlut to make a 65536 element lut, it will need numbers up to 65535 in the first column of the array of "points".

The Photoshop "curve" which I'm wanting to apply via maplut is just a two segment graph. All input values from black to about 90% white should map to black. Thereafter they should interpolate between black and white (see example Photoshop screenshot).

<img width="289" alt="screen shot 2016-07-08 at 2 20 22 pm" src="https://cloud.githubusercontent.com/assets/11267299/16677256/31c29a00-4517-11e6-8452-c2d297847a56.png">

I tried playing with identity(), but that builds either a 256 x 8-bit or 65536 x 16-bit lut.

Seems buildlut is the perfect tool, but need a way of specifying big numbers in the "x-axis" column. Or … perhaps there's a completely different and obvious way to do this… ?

Paul

**Comment by PaulHowson** [comment]
Tried another idea: make the 256 element 8-bit lut and then extend it to 65536 elements using resize:

```lut.resize(256.0, scale: 1.0)```

But then I get an error: "Vips::Error: No such option 'vscale' " … which is bizarre since the docs say vscale **is** an option. Hmmm I guess I can just resize it to 65536 x 256 elements and then crop off the bottom 255 elements … but really, the vscale option should work! You gotta love obstacle courses. :)

Paul

**Comment by PaulHowson** [comment]
So I did as above and cropped that lut to 65536 x 1 pixels. It is definitely an 8-bit depth image (confirmed by calling lut.format.to_i which says 8 bits) So… feeding that into maplut like this:

```mapped_img = source_img.maplut(lut)```

… and then writing mapped_img to a file, produces however a **16-bit image** (so says Photoshop and it's all black), _not an 8-bit image_. But if I generate the lut using Vips::Image.black to make a 65535 x 1 element image and then insert a 256 element ramp image at the end of that and then feed it into maplut, it produces an 8-bit output image with the levels mapped as expected. Truly weird. So close… Time for a break…

**Comment by jcupitt** [comment]
Hi Paul, the output type of `maplut` is set by the type of the lut, eg. if you make a 256 x 1 double lut and feed a uchar through it, you'll get a double image back. It makes sense if you think about it, otherwise it would have to throw away most of your lut as it cast the values down. 

Use `cast` to get the lut into the format you want for your output.  I'll try to make you an example.

**Comment by jcupitt** [comment]
Try this:

```
irb(main):025:0* x = Vips::Image.new_from_array [[0, 0], [60000, 0], [65535, 255]] => #<Vips::Image:0x195e858 ptr=0x22107d0>
irb(main):026:0> lut = Vips::Image.buildlut x=> #<Vips::Image:0x1addd00 ptr=0x2210320>
irb(main):027:0> lut = lut.cast "ushort"=> #<Vips::Image:0x1c23048 ptr=0x2210c80>
irb(main):028:0> lut.write_to_file "x.v"=> nil
```

It'd be nice if you could just do `Vips::Image.buildlut [[0, 0], ...]` and not need the intermediate image, I'll see if I can make that work.

**Comment by PaulHowson** [comment]
Yes, thanks, I understand how maplut is supposed to work and indeed it appears to be working correctly.

The problems seem to be with writing files. If I do:

```points = Vips::Image.new_from_array [ [0,0],  [224,0], [255,255] ]
lut8 = points.buildlut
lut8.write_to_file('lut-8bit.png')
lut8.write_to_file('lut-8bit.tif')```

This is making a 2 x 3 array of numbers for buildlut. Then buildlut creates an 8-bit lut with 256 x 1 elements. _All as you would expect_. But the png file when opened in Photoshop is shown as being 8-bits (Gray/8) _as you would expect_. The tif version of the same image when opened in Photoshop is shown as being 32-bits per channel (Gray/32). Surely the png and tif versions **of the same image** should have the same bit depth? I have attached both images (zipped since github does not support tif!).

[lut-8bit.zip](https://github.com/jcupitt/ruby-vips/files/353823/lut-8bit.zip)

Also, have you looked at the issue of img.resize not accepting the vscale option? It's not working here, but maybe it is at your end. I can work around that, but is that a bug or not?

Paul

**Comment by PaulHowson** [comment]
Oops. Seems I'm misinterpreting the result of img.format.to_i. Turns out theres a name method on format. Much clearer now. So it seems my 8-bit lut is actually double, which explains why its showing as 32-bit in Photoshop. Hold everything. Will keep digging.

**Comment by jcupitt** [comment]
I use nip2 and vips images for testing, it displays everything about a vips image with no extra conversions, so you can check what's really in an image. It's in brew, if you're on a mac.

**Comment by jcupitt** [comment]
Oh, the png writer will convert the double lut into 8 bits for saving, since PNG can't handle float. Save as `.v` and examine images in nip2.

**Comment by jcupitt** [comment]
`resize` should work. I see:

```
irb(main):030:0* lut.width
=> 65536
irb(main):031:0> lut.height
=> 1
irb(main):034:0> x = lut.resize 10, :vscale => 10
=> #<Vips::Image:0x1ebb8f0 ptr=0x233d640>
irb(main):035:0> x.width
=> 655360
irb(main):036:0> x.height
=> 10
```

**Comment by PaulHowson** [comment]
OK. I think I got it working. Causes of confusion:

- Not realising that buildlut creates a double image. It doesn't explicitly say that in the documentation, although the example shows fractional values in column 2, so I guess it's there. I assumed it would use the same kind of values supplied in the input image, in this case integers <255.

- Not realising that saving images in png format caused truncation to 8-bits. I was saving the lut and images as png and Photoshop was showing them as 8-bit, even though inside vips they were double.

- Not knowing how to get meaningful values from img.format. It returns a Vips::BandFormat, but there's no documentation saying how you turn that into a readable value. Turns out you use the name method. Had to find that by trial and error.

So it was a series of compounded errors on my part. Your irb example with casting the lut image helped.

Regarding nip2, yes it sounds like a good idea. I will look into installing it with brew.

Thanks for your help and your patience with my confusion.

Paul

**Comment by jcupitt** [comment]
Great! I'm glad it's working. 

You're right on `buildlut`, I added a note to the docs about the output format.

`.format` has a lot of overloads, you can do:

```
irb(main):002:0> im = Vips::Image.new_from_file "/home/john/Desktop/IMG_1867.JPG"
=> #<Vips::Image:0x13e9760 ptr=0x1a88010>
irb(main):003:0> im.format
=> #<Vips::BandFormat uchar>
irb(main):004:0> im.format == :uchar
=> true
irb(main):005:0> im.format == "uchar"
=> true
irb(main):007:0> im.format == 0
=> true
```

There are docs here:

http://www.rubydoc.info/gems/ruby-vips/1.0.0/Vips/BandFormat

Perhaps there should be a note in the intro as well.

**Comment by jcupitt** [comment]
It's just `brew install nip2`, by the way. It's an eccentric UI, to say the least.
